### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by shinank**
Update from the original project

### CODE REVIEW

**Comment by thaiat** [comment]
hi @shinank your PR are empty
the fact that you merge on your fork should not open a PR on the generator side

**Comment by jskrzypek** [comment]
@shinank You should be able to add the generator's repo as a remote in your local environment with
```sh
git remote add thaiat https://github.com/thaiat/generator-angular-famous-ionic.git
```

Then you can pull in updates to your local repo with 
```sh
git pull thaiat master
```

Finally you can push them up to your fork of the project with
```sh
git push origin master
```

**Comment by shinank** [comment]
Yes sorry in fault

**Comment by shinank** [comment]
@jskrzypek Thanks! That worked perfect. I appreciate the help.

**Comment by jskrzypek** [comment]
:+1:

**Pull request closed without merging**
